parameters:
    seguso.listener.ad_conf_email.class: SegundoUso\AdBundle\EventListener\AdConfirmationEmailListener

services:
    seguso.listener.ad_conf_email:
        class: %seguso.listener.ad_conf_email.class%
        arguments: [@mailer, @twig]
        tags:
            - { name: kernel.event_listener, event: seguso.ad_create.completed, method: onNewAdCreated }
