parameters:
    seguso.ad.util.random_string_generator.class: SegundoUso\AdBundle\Util\RandomStringGenerator

services:
    seguso.ad.util.random_string_generator:
        class: %seguso.ad.util.random_string_generator.class%
