segundo_uso_location_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SegundoUsoLocationBundle:Default:index }

#segundo_uso_location_list_municipalities:
#    path:  /location/list-municipalities
#    defaults: { _controller: SegundoUsoLocationBundle:Default:listMunicipalities }

segundo_uso_location_change_municipality:
    path:  /change-municipality
    defaults: { _controller: SegundoUsoLocationBundle:Default:changeMunicipality }