parameters:
    seguso.municipality_manager.class: SegundoUso\LocationBundle\Model\MunicipalityManager
    seguso.municipality.class: SegundoUso\LocationBundle\Entity\Municipality

services:
    seguso.municipality_manager:
        class: %seguso.municipality_manager.class%
        arguments: [@doctrine.orm.entity_manager, %seguso.municipality.class%]