parameters:
#    segundo_uso_location.example.class: SegundoUso\LocationBundle\Example

services:
#    segundo_uso_location.example:
#        class: %segundo_uso_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
