segundo_uso_announcement:
    resource: "@SegundoUsoAdBundle/Resources/config/routing.yml"
    prefix:   /

segundo_uso_frontend:
    resource: "@SegundoUsoFrontendBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine