segundo_uso_frontend_homepage:
    pattern:  /
    defaults: { _controller: SegundoUsoFrontendBundle:Home:home }

segundo_uso_frontend_ad_create:
    pattern: /anuncio/crear
    defaults: { _controller: SegundoUsoAdBundle:Default:create }

segundo_uso_frontend_ad_waiting_confirmation:
    pattern: /anuncio/por-confirmar
    defaults: { _controller: SegundoUsoAdBundle:Default:waitingConfirmation }

segundo_uso_frontend_ad_confirmation:
    pattern: /anuncio/confirmacion/{pid}
    defaults: { _controller: SegundoUsoAdBundle:Default:confirmation }

segundo_uso_frontend_ad_list:
    pattern: /anuncios
    defaults: { _controller: SegundoUsoAdBundle:Default:index }

segundo_uso_frontend_ad_show:
    pattern: /anuncios/{pid}
    defaults: { _controller: SegundoUsoAdBundle:Default:show }