parameters:
    seguso.listener.default_municipality.class: SegundoUso\CoreBundle\EventListener\DefaultMunicipalityListener

services:
    seguso.listener.default_municipality:
        class: %seguso.listener.default_municipality.class%
        arguments: [@seguso.municipality_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
