parameters:
#    segundo_uso_behat.example.class: SegundoUso\BehatBundle\Example

services:
#    segundo_uso_behat.example:
#        class: %segundo_uso_behat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
